name: main 

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - uses: c-hive/gha-yarn-cache@v2
      - name: Install JS dependencies
        run: yarn install
      
      - run: set DEBUG=jsreport&&yarn workspace jsreport-fs-store test